### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by zummenix** [BardRedStar/EasyStartGuide#1]
Does it need to be a singleton? I imagine, every view controller will have it's own `EasyStartGuide` with slightly different options:
https://github.com/BardRedStar/EasyStartGuide/blob/f42f45f9e9119494c0005cdef8e31521070731bb/EasyStartGuide/Classes/EasyStartGuide.swift#L15-L17

Typo:
https://github.com/BardRedStar/EasyStartGuide/blob/f42f45f9e9119494c0005cdef8e31521070731bb/EasyStartGuide/Classes/EasyStartGuideModels.swift#L26-L27

Use `if let`:
https://github.com/BardRedStar/EasyStartGuide/blob/f42f45f9e9119494c0005cdef8e31521070731bb/EasyStartGuide/Classes/LessonPopoverViewContoller.swift#L134-L139

**Comment by BardRedStar** [comment]
Thanks for code review!
